const D=window.LEAGUE_DATA;
const byId=Object.fromEntries(D.teams.map(t=>[t.team,t]));
const fmt=n=>Number(n).toFixed(1);
function table(headers,rows){return `<table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
document.querySelectorAll('.tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.getElementById(btn.dataset.tab).classList.add('active')}));
const sorted=[...D.teams].sort((a,b)=>b.points-a.points);
document.getElementById('standingsTable').innerHTML=table(['Pos','Team','Pts','Projected'],sorted.slice(0,12).map(t=>[t.position,`#${t.team} ${t.name}`,fmt(t.points),fmt(t.projected)]));
document.getElementById('bubbleTable').innerHTML=table(['Pos','Team','Pts','Gap'],sorted.slice(12,18).map(t=>[t.position,`#${t.team} ${t.name}`,fmt(t.points),fmt(Math.max(0,44-t.points))]));
const motw=D.round10[0],ma=byId[motw.a],mb=byId[motw.b];
document.getElementById('weekHeadline').innerHTML=`<div class="eyebrow">MATCH OF THE WEEK</div><h2>#${ma.team} ${ma.name} vs #${mb.team} ${mb.name}</h2><p>Impact score <strong>${motw.impact}/100</strong>. This matchup carries the biggest combined effect on playoff positioning, bubble pressure, and separation entering Round 10.</p>`;
document.getElementById('matchupTable').innerHTML=table(['Rank','Matchup','Impact','Implication'],D.round10.map((m,i)=>{const a=byId[m.a],b=byId[m.b],cls=m.impact>=80?'high':m.impact>=55?'med':'low';const imp=(a.position<=12&&b.position<=12)?'Seeding and cushion':((a.position<=16||b.position<=16)?'Direct bubble pressure':'Spoiler opportunity');return[i+1,`#${a.team} ${a.name}<br><small>vs</small><br>#${b.team} ${b.name}`,`<span class="impact ${cls}">${m.impact}</span>`,imp]}));
document.getElementById('sosTable').innerHTML=table(['Rank','Team','SOS','Avg Opp Pts','Top 8','Bubble','Difficulty'],D.sos.map(x=>{const t=byId[x.team],diff=x.score>=80?'Brutal':x.score>=65?'Very hard':x.score>=50?'Difficult':x.score>=35?'Average':x.score>=20?'Favorable':'Easiest';return[x.rank,`#${t.team} ${t.name}`,fmt(x.score),fmt(x.avgOppPts),x.top8,x.bubble,diff]}));
const power=[...D.teams].sort((a,b)=>(b.points*.45+b.last3*5*.30+(100-b.sosScore)*.15)-(a.points*.45+a.last3*5*.30+(100-a.sosScore)*.15));
document.getElementById('powerTable').innerHTML=table(['Rank','Team','Pts','3-Wk Avg','SOS'],power.map((t,i)=>[i+1,`#${t.team} ${t.name}`,fmt(t.points),fmt(t.last3),t.sosRank]));
document.getElementById('trendTable').innerHTML=table(['Team','Trend','3-Wk','Season'],[...D.teams].sort((a,b)=>b.last3-a.last3).map(t=>[`#${t.team} ${t.name}`,t.trend,fmt(t.last3),fmt(t.seasonAvg)]));
const select=document.getElementById('teamSelect');[...D.teams].sort((a,b)=>a.team-b.team).forEach(t=>{const o=document.createElement('option');o.value=t.team;o.textContent=`Team ${t.team} — ${t.name}`;select.appendChild(o)});select.value=11;
function renderTeam(){const t=byId[Number(select.value)],s=D.sos.find(x=>x.team===t.team),rows=s.opps.map((o,i)=>[10+i,D.dates[String(10+i)],`#${o} ${byId[o].name}`,byId[o].position,fmt(byId[o].points)]);document.getElementById('teamView').innerHTML=`<div class="team-grid"><div class="metric"><span>Current position</span><strong>${t.position}</strong></div><div class="metric"><span>Current points</span><strong>${fmt(t.points)}</strong></div><div class="metric"><span>3-week average</span><strong>${fmt(t.last3)}</strong></div><div class="metric"><span>SOS rank</span><strong>${t.sosRank}</strong></div></div><div class="grid two"><div class="card"><div class="card-head"><h2>${t.name}</h2><span>${t.position<=12?'IN':t.position<=16?'BUBBLE':'OUT'}</span></div><p>Projected finish points: <strong>${fmt(t.projected)}</strong></p><p>Trend: <strong>${t.trend}</strong> · Net scoring average: <strong>${fmt(t.netAvg)}</strong></p><div class="bar"><span style="width:${Math.min(100,t.points/80*100)}%"></span></div></div><div class="card"><div class="card-head"><h2>Remaining opponents</h2><span>Rounds 10–16</span></div>${table(['Round','Date','Opponent','Pos','Pts'],rows)}</div></div>`}
select.addEventListener('change',renderTeam);renderTeam();
document.getElementById('strokeTable').innerHTML=table(['Rank','Team','Gross Avg','Net Avg','Current Pos'],[...D.teams].sort((a,b)=>a.netAvg-b.netAvg).map((t,i)=>[i+1,`#${t.team} ${t.name}`,fmt(t.grossAvg),fmt(t.netAvg),t.position]));
