const D=window.LEAGUE_DATA,byId=Object.fromEntries(D.teams.map(t=>[t.team,t])),fmt=n=>Number(n).toFixed(1);
const status=t=>t.position<=12?'IN':t.position<=16?'BUBBLE':'OUT',cls=s=>s==='IN'?'in':s==='BUBBLE'?'bubble':'out';
function table(h,r){return `<table><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${r.map(row=>`<tr>${row.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.tab).classList.add('active')}));
const sorted=[...D.teams].sort((a,b)=>b.points-a.points||a.position-b.position);
const S=D.storylines,big=byId[S.biggestWeek],rise=byId[S.biggestRiser],hot=byId[S.hottest],hard=byId[S.hardestSOS];
document.getElementById('headlineHero').innerHTML=`<div class="eyebrow">ROUND 10 RECAP</div><h2>${big.name} posts the week's biggest result</h2><p>Team ${big.team} earned <strong>${fmt(big.weekPoints)} points</strong>. The playoff cutoff now sits at ${fmt(D.meta.currentCutoff)}, with only ${D.meta.roundsLeft} regular-season rounds remaining.</p>`;
document.getElementById('storyCards').innerHTML=[
['Biggest week',big.name,`${fmt(big.weekPoints)} points`],['Biggest riser',rise.name,`${rise.positionMove>0?'+':''}${rise.positionMove} places`],
['Hottest team',hot.name,`${fmt(hot.last3)} pts/round — last 3`],['Hardest road',hard.name,`SOS rank #${hard.sosRank}`]
].map(x=>`<div class="story-card"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('');
document.getElementById('standingsTable').innerHTML=table(['Pos','Team','Pts','Week','Odds','Status'],sorted.map(t=>[t.position,`#${t.team} ${t.name}`,fmt(t.points),fmt(t.weekPoints),`${t.playoffOdds}%`,`<span class="pill ${cls(status(t))}">${status(t)}</span>`]));
document.getElementById('bubbleTable').innerHTML=table(['Pos','Team','Pts','Gap','Need Avg'],sorted.filter(t=>t.position>=9&&t.position<=18).map(t=>[t.position,`#${t.team} ${t.name}`,fmt(t.points),fmt(Math.max(0,D.meta.currentCutoff-t.points)),fmt(t.neededAvg)]));
document.getElementById('playoffCards').innerHTML=[
['Current cutoff',fmt(D.meta.currentCutoff),'Top 12 qualify'],['Projected cutoff',fmt(D.meta.projectedCut),'Five points per remaining round'],
['Rounds left',D.meta.roundsLeft,'60 points available'],['Playoff format','Stroke play','Regular season is match play']
].map(x=>`<div class="hero-card"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('');
document.getElementById('playoffTable').innerHTML=table(['Pos','Team','Pts','Odds','Projected','Need Avg','SOS','Destiny'],sorted.map(t=>[t.position,`#${t.team} ${t.name}`,fmt(t.points),`${t.playoffOdds}%`,fmt(t.projected),fmt(t.neededAvg),t.sosRank,t.controlsDestiny?'Controls':'Needs help']));
const motw=D.nextMatchups[0],ma=byId[motw.a],mb=byId[motw.b];
document.getElementById('weekHeadline').innerHTML=`<div class="eyebrow">ROUND 11 MATCH OF THE WEEK</div><h2>#${ma.team} ${ma.name} vs #${mb.team} ${mb.name}</h2><p>Playoff impact <strong>${motw.impact}/100</strong>. The ranking weighs current position, direct bubble pressure, points separation, and top-seed implications.</p>`;
document.getElementById('matchupTable').innerHTML=table(['Rank','Matchup','Impact','Implication'],D.nextMatchups.map((m,i)=>{const a=byId[m.a],b=byId[m.b],ic=m.impact>=80?'high':m.impact>=55?'med':'low';let imp=(a.position<=12&&b.position<=12)?'Seeding and playoff cushion':((a.position<=16||b.position<=16)?'Direct bubble pressure':'Spoiler opportunity');return[i+1,`#${a.team} ${a.name}<br><small>vs</small><br>#${b.team} ${b.name}`,`<span class="impact ${ic}">${m.impact}</span>`,imp]}));
document.getElementById('sosTable').innerHTML=table(['Rank','Team','SOS','Avg Opp Pts','Top 8','Top 12','Bubble','Difficulty'],D.sos.map(x=>{const t=byId[x.team],d=x.score>=80?'Brutal':x.score>=65?'Very hard':x.score>=50?'Difficult':x.score>=35?'Average':x.score>=20?'Favorable':'Easiest';return[x.rank,`#${t.team} ${t.name}`,fmt(x.score),fmt(x.avgOppPts),x.top8,x.top12,x.bubble,d]}));
const power=[...D.teams].sort((a,b)=>(b.points*.43+b.last3*5*.30+(100-b.sosScore)*.14+(100-(b.netAvg||40)*2)*.13)-(a.points*.43+a.last3*5*.30+(100-a.sosScore)*.14+(100-(a.netAvg||40)*2)*.13));
document.getElementById('powerTable').innerHTML=table(['Rank','Team','Pts','3-Wk','Net Avg','SOS'],power.map((t,i)=>[i+1,`#${t.team} ${t.name}`,fmt(t.points),fmt(t.last3),fmt(t.netAvg),t.sosRank]));
document.getElementById('trendTable').innerHTML=table(['Team','Trend','3-Wk','5-Wk','Move','Field W-L-T'],[...D.teams].sort((a,b)=>b.last3-a.last3).map(t=>[`#${t.team} ${t.name}`,t.trend,fmt(t.last3),fmt(t.last5),`${t.positionMove>0?'+':''}${t.positionMove}`,`${t.fieldWins}-${t.fieldLosses}-${t.fieldTies}`]));
const sim=document.getElementById('simControls');D.nextMatchups.forEach((m,i)=>{let a=byId[m.a],b=byId[m.b];sim.innerHTML+=`<div class="sim-row"><label>#${a.team} ${a.name}<br>vs<br>#${b.team} ${b.name}</label><input id="sim${i}" type="number" min="0" max="10" step=".5" value="5"><small>Points for Team ${a.team}; opponent gets the remainder</small></div>`});
function runSim(){const p=Object.fromEntries(D.teams.map(t=>[t.team,t.points]));D.nextMatchups.forEach((m,i)=>{let x=Number(document.getElementById('sim'+i).value);p[m.a]+=x;p[m.b]+=10-x});const rows=[...D.teams].sort((a,b)=>p[b.team]-p[a.team]).map((t,i)=>[i+1,`#${t.team} ${t.name}`,fmt(p[t.team]),i<12?'IN':'OUT']);document.getElementById('simTable').innerHTML=table(['Pos','Team','Projected Pts','Status'],rows)}document.getElementById('runSim').addEventListener('click',runSim);runSim();
const sel=document.getElementById('teamSelect');[...D.teams].sort((a,b)=>a.team-b.team).forEach(t=>{let o=document.createElement('option');o.value=t.team;o.textContent=`Team ${t.team} — ${t.name}`;sel.appendChild(o)});sel.value=11;
function renderTeam(){const t=byId[+sel.value],s=D.sos.find(x=>x.team===t.team),rows=s.opps.map((o,i)=>[11+i,D.dates[String(11+i)],`#${o} ${byId[o].name}`,byId[o].position,fmt(byId[o].points)]);document.getElementById('teamView').innerHTML=`<div class="team-grid"><div class="metric"><span>Position</span><strong>${t.position}</strong></div><div class="metric"><span>Playoff odds</span><strong>${t.playoffOdds}%</strong></div><div class="metric"><span>3-week average</span><strong>${fmt(t.last3)}</strong></div><div class="metric"><span>SOS rank</span><strong>${t.sosRank}</strong></div></div><div class="grid two"><div class="card"><div class="card-head"><h2>${t.name}</h2><span>${status(t)}</span></div><p>Projected finish: <strong>${fmt(t.projected)} points</strong></p><p>Needed average to reach ${fmt(D.meta.projectedCut)}: <strong>${fmt(t.neededAvg)}</strong></p><p>Round 10: <strong>${fmt(t.weekPoints)} points</strong> · Net stroke score: <strong>${fmt(t.round10Net)}</strong></p><p>Season net average: <strong>${fmt(t.netAvg)}</strong> · Field record: <strong>${t.fieldWins}-${t.fieldLosses}-${t.fieldTies}</strong></p><div class="bar"><span style="width:${t.playoffOdds}%"></span></div></div><div class="card"><div class="card-head"><h2>Remaining opponents</h2><span>Rounds 11–16</span></div>${table(['Round','Date','Opponent','Pos','Pts'],rows)}</div></div>`}sel.addEventListener('change',renderTeam);renderTeam();
document.getElementById('strokeTable').innerHTML=table(['Rank','Team','Net Avg','Gross Avg','R10 Net','R10 Gross','Playoff Status'],[...D.teams].sort((a,b)=>(a.netAvg||99)-(b.netAvg||99)).map((t,i)=>[i+1,`#${t.team} ${t.name}`,fmt(t.netAvg),fmt(t.grossAvg),fmt(t.round10Net),fmt(t.round10Gross),status(t)]));
